export type DensityGroup = 'KG60_PER_CUBICMETRE' |
    'KG90_PER_CUBICMETRE' |
    'KG120_PER_CUBICMETRE' |
    'KG160_PER_CUBICMETRE' |
    'KG220_PER_CUBICMETRE' |
    'KG250_PER_CUBICMETRE' |
    'KG300_PER_CUBICMETRE' |
    'KG400_PER_CUBICMETRE' |
    'KG600_PER_CUBICMETRE' |
    'KG950_PER_CUBICMETRE'
